# version: "3"

services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=atc
    - MYSQL_CHARACTER_SET_SERVER=utf8mb4
    - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
  app:
    container_name: atc_app
    build: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app/train_model.py:/app/train_model.py